---
# name: requirements.yml
# description: This file contains dependencies.
# author: while-true-do.io
# contact: hello@while-true-do.io
# license: BSD-3-Clause

- src: while_true_do.srv_docker
- src: while_true_do.srv_kvm
- src: while_true_do.srv_pcp
- src: while_true_do.srv_podman
- src: while_true_do.sys_kdump
- src: while_true_do.sys_selinux
- src: while_true_do.sys_tuned
