---
# tasks file for while_true_do.srv_cockpit

- name: Manage Cockpit Web Packages
  package:
    name: "{{ wtd_srv_cockpit_web_package }}"
    state: "{{ wtd_srv_cockpit_web_package_state }}"
  become: true
  tags:
    - cockpit
    - package
    - system
    - web

- name: Configure Cockpit Web
  template:
    src: "cockpit.conf.j2"
    dest: "/etc/cockpit/cockpit.conf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when:
    - wtd_srv_cockpit_web_package_state != "absent"
  notify:
    - Restart Cockpit Web
  tags:
    - cockpit
    - configuration
    - system
    - web

- name: Manage Cockpit Web Dashboard Packages
  package:
    name: "{{ wtd_srv_cockpit_web_dash_package }}"
    state: "{{ wtd_srv_cockpit_web_dash_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_web_dash_package_state != "unmanaged"
  tags:
    - cockpit
    - package
    - system
    - web

- name: Configure Cockpit Web Dashboard Clients
  template:
    src: "99-webui.json.j2"
    dest: "/etc/cockpit/machines.d/99-webui.json"
    owner: "root"
    group: "root"
    mode: 0644
    lstrip_blocks: true
  become: true
  when:
    - wtd_srv_cockpit_web_dash_package_state != "unmanaged"
    - wtd_srv_cockpit_web_conf_clients is defined
  notify:
    - Restart Cockpit Web
  tags:
    - cockpit
    - configuration
    - system
    - web

- name: Manage Cockpit Web Service
  service:
    name: "{{ wtd_srv_cockpit_web_service }}"
    state: "{{ wtd_srv_cockpit_web_service_state }}"
    enabled: "{{ wtd_srv_cockpit_web_service_enabled }}"
  become: true
  when:
    - wtd_srv_cockpit_web_package_state != "absent"
  tags:
    - cockpit
    - service
    - system
    - web

- name: Manage Cockpit Web Firewalld Service
  firewalld:
    service: "{{ wtd_srv_cockpit_web_fw_service }}"
    state: "{{ wtd_srv_cockpit_web_fw_service_state }}"
    zone: "{{ wtd_srv_cockpit_web_fw_service_zone }}"
    immediate: true
    permanent: true
  become: true
  when:
    - wtd_srv_cockpit_web_fw_mgmt
  tags:
    - cockpit
    - configuration
    - firewall
    - security
