---
# tasks file for while_true_do.srv_cockpit

- name: Include distribution Vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - cockpit
    - package
    - system

- name: Include distribution Tasks
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == "RedHat"
  tags:
    - cockpit
    - package
    - system

- name: Manage Cockpit system Packages
  package:
    name: "{{ wtd_srv_cockpit_sys_package }}"
    state: "{{ wtd_srv_cockpit_sys_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_sys_package_state != "unmanaged"
  tags:
    - cockpit
    - package
    - system

- name: Manage Cockpit packagekit Packages
  package:
    name: "{{ wtd_srv_cockpit_pk_package }}"
    state: "{{ wtd_srv_cockpit_pk_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_pk_package_state != "unmanaged"
  tags:
    - cockpit
    - package
    - system

- name: Manage Cockpit pcp Packages
  package:
    name: "{{ wtd_srv_cockpit_pcp_package }}"
    state: "{{ wtd_srv_cockpit_pcp_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_pcp_package_state != "unmanaged"
  tags:
    - cockpit
    - package
    - pcp
    - system

- name: Manage Cockpit docker Packages
  package:
    name: "{{ wtd_srv_cockpit_docker_package }}"
    state: "{{ wtd_srv_cockpit_docker_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_docker_package_state != "unmanaged"
  tags:
    - cockpit
    - container
    - package
    - system

- name: Manage Cockpit podman Packages
  package:
    name: "{{ wtd_srv_cockpit_podman_package }}"
    state: "{{ wtd_srv_cockpit_podman_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_podman_package_state != "unmanaged"
  tags:
    - cockpit
    - container
    - package
    - system

- name: Manage Cockpit machines Packages
  package:
    name: "{{ wtd_srv_cockpit_machines_package }}"
    state: "{{ wtd_srv_cockpit_machines_package_state }}"
  become: true
  when:
    - wtd_srv_cockpit_machines_package_state != "unmanaged"
  tags:
    - cockpit
    - package
    - system
    - virtualization

- name: Include Cockpit web Tasks
  include_tasks: cockpit-web.yml
  when:
    - wtd_srv_cockpit_web_package_state != "unmanaged"
  tags:
    - cockpit
    - web
    - package
    - system
