---
- name: Converge
  hosts: all
  roles:
    - role: while_true_do.srv_cockpit
      wtd_srv_cockpit_role: "all"
      wtd_srv_cockpit_web_conf_clients:
        - name: "192.168.0.10"
        - name: "host2"
        - name: "host3.example.com"
